import { useCallback, useState } from 'react';
import { useFocusEffect } from '@react-navigation/native';
import { FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import { getDocumentStats, listDocuments } from '../db/database';
import { formatMoney } from '../utils/format';
import FilterSelect from '../components/FilterSelect';
const date = (value) => value ? new Date(value).toLocaleDateString('fr-FR') : '';

export default function HistoryScreen({ navigation }) {
  const [documents, setDocuments] = useState([]);
  const [type, setType] = useState('');
  const [status, setStatus] = useState('');
  const [stats, setStats] = useState({ total: 0, devis: 0, factures: 0, brouillons: 0, payes: 0, envoyes: 0, montantTotal: 0, montantPaye: 0, montantAttente: 0 });
  const refresh = useCallback(() => { Promise.all([listDocuments({ type, statut: status }), getDocumentStats({ type, statut: status })]).then(([nextDocuments, nextStats]) => { setDocuments(nextDocuments); setStats(nextStats); }).catch(() => {}); }, [status, type]);
  useFocusEffect(useCallback(() => { refresh(); }, [refresh]));
  return <View style={styles.screen}><Text style={styles.heading}>Historique global</Text><Text style={styles.helper}>Suivez votre activité et affinez l’affichage avec les sélecteurs.</Text><View style={styles.kpiGrid}><View style={styles.kpi}><Text style={styles.kpiLabel}>DOCUMENTS</Text><Text style={styles.kpiValue}>{stats.total}</Text><Text style={styles.kpiHint}>{stats.devis} devis · {stats.factures} factures</Text></View><View style={styles.kpi}><Text style={styles.kpiLabel}>ENVOYÉS</Text><Text style={styles.kpiValue}>{stats.envoyes}</Text><Text style={styles.kpiHint}>{stats.brouillons} brouillons</Text></View><View style={styles.kpiWide}><Text style={styles.kpiLabelLight}>MONTANT TOTAL</Text><Text style={styles.kpiValueLight}>{formatMoney(stats.montantTotal)}</Text><Text style={styles.kpiHintLight}>Payé : {formatMoney(stats.montantPaye)}</Text></View><View style={styles.kpiWarning}><Text style={styles.kpiLabelLight}>À ENCAISSER</Text><Text style={styles.kpiValueLight}>{formatMoney(stats.montantAttente)}</Text><Text style={styles.kpiHintLight}>Factures non réglées</Text></View></View><View style={styles.filters}><FilterSelect label="Type" value={type} onChange={setType} options={[{ label: 'Tous les documents', value: '' }, { label: 'Devis uniquement', value: 'devis' }, { label: 'Factures uniquement', value: 'facture' }]} /><FilterSelect label="Statut" value={status} onChange={setStatus} options={[{ label: 'Tous les statuts', value: '' }, { label: 'Brouillons', value: 'brouillon' }, { label: 'Payés', value: 'payé' }, { label: 'Annulés', value: 'annulé' }]} /></View><FlatList data={documents} keyExtractor={(item) => String(item.id)} ListEmptyComponent={<Text style={styles.empty}>Aucun événement à afficher.</Text>} renderItem={({ item }) => <Pressable style={styles.row} onPress={() => navigation.navigate('DocumentDetail', { id: item.id })}><View><Text style={styles.number}>{item.numero}</Text><Text style={styles.detail}>{item.client_nom || 'Sans client'} · {date(item.date_creation)}</Text></View><View><Text style={styles.total}>{formatMoney(item.total)}</Text><Text style={styles.detail}>{item.type} · {item.statut}</Text></View></Pressable>} /></View>;
}

const styles = StyleSheet.create({ screen: { backgroundColor: '#F5F8FC', flex: 1, padding: 20 }, heading: { color: '#1459C7', fontSize: 26, fontWeight: '800', marginBottom: 6 }, helper: { color: '#607A9F', fontSize: 13, marginBottom: 16 }, kpiGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginBottom: 18 }, kpi: { backgroundColor: '#FFFFFF', borderColor: '#D7E5F5', borderRadius: 10, borderWidth: 1, padding: 14, width: '48%' }, kpiWide: { backgroundColor: '#1459C7', borderRadius: 10, padding: 14, width: '48%' }, kpiWarning: { backgroundColor: '#1677FF', borderRadius: 10, padding: 14, width: '48%' }, kpiLabel: { color: '#7892B8', fontSize: 10, fontWeight: '900', letterSpacing: 1 }, kpiValue: { color: '#1459C7', fontSize: 22, fontWeight: '900', marginTop: 10 }, kpiHint: { color: '#7892B8', fontSize: 11, marginTop: 5 }, kpiLabelLight: { color: '#D7E5FF', fontSize: 10, fontWeight: '900', letterSpacing: 1 }, kpiValueLight: { color: '#FFFFFF', fontSize: 18, fontWeight: '900', marginTop: 10 }, kpiHintLight: { color: '#D7E5FF', fontSize: 11, marginTop: 5 }, filters: { gap: 10, marginBottom: 18 }, row: { alignItems: 'center', backgroundColor: '#FFFFFF', borderBottomColor: '#DDE7F5', borderBottomWidth: 1, flexDirection: 'row', justifyContent: 'space-between', minHeight: 74, paddingHorizontal: 14 }, number: { color: '#1459C7', fontSize: 15, fontWeight: '800' }, detail: { color: '#7B847D', fontSize: 12, marginTop: 4, textTransform: 'capitalize' }, total: { color: '#1677FF', fontWeight: '800', textAlign: 'right' }, empty: { color: '#7B847D', padding: 20, textAlign: 'center' } });
