import { useCallback, useState } from 'react';
import { useFocusEffect } from '@react-navigation/native';
import { Alert, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { exportBackup } from '../utils/backup';
import { getCompany, resetLocalData, saveCompany } from '../db/database';

const defaults = { currency: 'F CFA', devisePrefix: 'DEV-', facturePrefix: 'FAC-', validityDays: '30', paymentDays: '30', defaultStatus: 'brouillon', discount: '0', deliveryFee: '0', dateFormat: 'DD/MM/YYYY', theme: 'clair', showLogoPdf: true, showBankPdf: true, automaticBackup: false, unpaidReminders: false, dueReminders: false, conversionNotification: true, filePrefix: 'quickdevis', generalConditions: '', footer: '', bankDetails: '', model: 'standard' };

export default function SettingsScreen({ navigation }) {
  const [company, setCompany] = useState({ nom: '', adresse: '', telephone: '', email: '', logo_uri: '', ...defaults });
  useFocusEffect(useCallback(() => { getCompany().then((saved) => { if (saved) setCompany({ ...defaults, ...saved, ...(saved.settings || {}) }); }).catch(() => {}); }, []));
  const update = (field, value) => setCompany((current) => ({ ...current, [field]: value }));
  async function save() { await saveCompany({ ...company, settings: company }); Alert.alert('Paramètres enregistrés', 'Vos réglages seront utilisés dans les prochains documents.'); }
  async function backup() { try { await exportBackup(); } catch { Alert.alert('Erreur', 'Impossible de créer la sauvegarde.'); } }
  function reset() { Alert.alert('Réinitialiser les données ?', 'Cette action supprime clients, produits, documents et paramètres.', [{ text: 'Annuler', style: 'cancel' }, { text: 'Réinitialiser', style: 'destructive', onPress: async () => { await resetLocalData(); setCompany({ nom: '', adresse: '', telephone: '', email: '', ...defaults }); Alert.alert('Données supprimées', 'La base locale est vide.'); } }]); }
  const field = (key, placeholder, extra = {}) => <TextInput style={styles.input} placeholder={placeholder} placeholderTextColor="#7892B8" value={String(company[key] || '')} onChangeText={(value) => update(key, value)} {...extra} />;
  const toggle = (key, label, hint) => <View style={styles.settingRow}><View style={styles.settingCopy}><Text style={styles.settingLabel}>{label}</Text><Text style={styles.settingHint}>{hint}</Text></View><Switch value={Boolean(company[key])} onValueChange={(value) => update(key, value)} trackColor={{ false: '#D7E5F5', true: '#8DBAFF' }} thumbColor={company[key] ? '#1677FF' : '#FFFFFF'} /></View>;
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><Text style={styles.kicker}>CENTRE DE CONFIGURATION</Text><Text style={styles.title}>Paramètres</Text><Text style={styles.subtitle}>Personnalisez QuickDevis selon votre activité.</Text>
  <Section title="Entreprise" description="Ces informations apparaissent sur vos documents.">{field('nom', 'Nom de l’entreprise')}{field('adresse', 'Adresse')}{field('telephone', 'Téléphone', { keyboardType: 'phone-pad' })}{field('email', 'Email', { keyboardType: 'email-address', autoCapitalize: 'none' })}{field('logo_uri', 'URI du logo (optionnel)')}{field('bankDetails', 'Coordonnées bancaires (optionnel)', { multiline: true })}</Section>
  <Section title="Documents" description="Configurez la numérotation et les règles commerciales.">{field('devisePrefix', 'Préfixe des devis')}{field('facturePrefix', 'Préfixe des factures')}{field('validityDays', 'Validité des devis (jours)', { keyboardType: 'number-pad' })}{field('paymentDays', 'Délai de paiement (jours)', { keyboardType: 'number-pad' })}{field('discount', 'Remise par défaut (%)', { keyboardType: 'decimal-pad' })}{field('deliveryFee', 'Frais de livraison par défaut', { keyboardType: 'decimal-pad' })}{field('generalConditions', 'Conditions générales', { multiline: true })}{field('footer', 'Pied de page des documents', { multiline: true })}</Section>
  <Section title="Apparence et PDF" description="Préparez un rendu cohérent et professionnel."><Text style={styles.staticValue}>Devise : F CFA</Text><Text style={styles.staticValue}>Format de date : {company.dateFormat}</Text>{toggle('showLogoPdf', 'Afficher le logo', 'Inclure le logo dans les PDF.')}{toggle('showBankPdf', 'Afficher les coordonnées bancaires', 'Ajouter les coordonnées au document.')}</Section>
  <Section title="Sauvegarde et données" description="Vos données restent locales sur cet appareil.">{toggle('automaticBackup', 'Sauvegarde automatique', 'Préparer une sauvegarde lors des actions importantes.')}</Section><Pressable style={styles.primaryButton} onPress={save}><Text style={styles.primaryText}>Enregistrer tous les paramètres</Text></Pressable><Pressable style={styles.secondaryButton} onPress={backup}><Text style={styles.secondaryText}>Exporter une sauvegarde JSON</Text></Pressable><Pressable style={styles.guideButton} onPress={() => navigation.navigate('Guide')}><Text style={styles.guideText}>Ouvrir le guide d’utilisation</Text></Pressable><Pressable style={styles.dangerButton} onPress={reset}><Text style={styles.dangerText}>Réinitialiser les données locales</Text></Pressable></ScrollView>;
}

function Section({ title, description, children }) { return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text><Text style={styles.sectionDescription}>{description}</Text>{children}</View>; }

const styles = StyleSheet.create({ screen: { backgroundColor: '#F5F8FC', flex: 1 }, content: { padding: 20, paddingBottom: 50 }, kicker: { color: '#1677FF', fontSize: 11, fontWeight: '900', letterSpacing: 1.4 }, title: { color: '#1459C7', fontSize: 30, fontWeight: '900', marginTop: 6 }, subtitle: { color: '#607A9F', fontSize: 14, marginBottom: 18, marginTop: 6 }, section: { backgroundColor: '#FFFFFF', borderColor: '#D7E5F5', borderRadius: 12, borderWidth: 1, marginBottom: 14, padding: 16 }, sectionTitle: { color: '#1459C7', fontSize: 18, fontWeight: '900' }, sectionDescription: { color: '#7892B8', fontSize: 12, lineHeight: 18, marginBottom: 14, marginTop: 4 }, input: { backgroundColor: '#F8FBFF', borderColor: '#BFD3F7', borderRadius: 8, borderWidth: 1, color: '#1459C7', fontSize: 14, marginBottom: 10, minHeight: 48, paddingHorizontal: 13, paddingVertical: 12 }, staticValue: { backgroundColor: '#E9F1FF', borderRadius: 8, color: '#1459C7', fontWeight: '800', marginBottom: 8, padding: 13 }, settingRow: { alignItems: 'center', borderBottomColor: '#E5EDF8', borderBottomWidth: 1, flexDirection: 'row', justifyContent: 'space-between', minHeight: 68 }, settingCopy: { flex: 1, paddingRight: 16 }, settingLabel: { color: '#1459C7', fontSize: 14, fontWeight: '800' }, settingHint: { color: '#7892B8', fontSize: 11, lineHeight: 16, marginTop: 3 }, primaryButton: { alignItems: 'center', backgroundColor: '#1677FF', borderRadius: 9, justifyContent: 'center', minHeight: 52, marginBottom: 10 }, primaryText: { color: '#FFFFFF', fontWeight: '900' }, secondaryButton: { alignItems: 'center', borderColor: '#1677FF', borderRadius: 9, borderWidth: 1, justifyContent: 'center', minHeight: 50, marginBottom: 10 }, secondaryText: { color: '#1677FF', fontWeight: '900' }, guideButton: { alignItems: 'center', backgroundColor: '#1459C7', borderRadius: 9, justifyContent: 'center', minHeight: 50, marginBottom: 10 }, guideText: { color: '#FFFFFF', fontWeight: '900' }, dangerButton: { alignItems: 'center', justifyContent: 'center', minHeight: 46 }, dangerText: { color: '#B45A3C', fontSize: 13, fontWeight: '800' } });
